### ISSUE TITLE
Changing settings?

### ISSUE THREAD

**Issue by wesbz** [JoseExposito/gnome-shell-extension-x11gestures#1] opened 2021-03-04 22:35 UTC
### Is your feature request related to a problem? Please describe

When I activate the extension, only the 4 fingers UP/DOWN swipe works on changing workspaces but I cannot do anything else as smoothly as you show in the repo's GIF.

### Describe the solution you'd like

Having settings for the extension?

### Describe alternatives you've considered

Having the extension to read the touchegg config file?

Thanks in advance for your help.

**Comment by JoseExposito** [comment] 2021-03-05 06:41
Hello, and thanks for your issue report.

I guess you are running GNOME 3.36 or 3.38. Those version of GNOME only have a 1 to 1 animation for switching workspaces. The GIF is recorded in GNOME 40 beta. You'll notice that in addition to the animations the layout and app menu is completely different.

Closing the issue as for your version of GNOME that's the intended behavior.

**Closed by JoseExposito** 2021-03-05 06:41 UTC

**Comment by wesbz** [comment] 2021-03-05 15:17
True! Thanks for your explanation! Too bad it doesn't combine well with the grid workspace extension to navigate freely between all workspaces!
