### ISSUE TITLE
Swipes are too long on gnome 40

### ISSUE THREAD

**Issue by andirsun** [JoseExposito/gnome-shell-extension-x11gestures#29] opened 2021-11-01 17:49 UTC
### Describe the bug

Swipes with 3 fingers are too long to trigger the actions (my touchpad is big). 

### Expected behaviour

Tell us what should happen.

### Actual behaviour

https://user-images.githubusercontent.com/22928302/139719875-76c9a328-4ac6-4da1-8c70-cf3e73a6fcb4.mp4

### Logs

If required, include logs of the bug:

```
$ journalctl -f -o cat /usr/bin/gnome-shell

```

Attach Touchégg configuration, placed at `~/.config/touchegg/touchegg.conf`, if you consider it
relevant.

### Your environment

 * Extension version: last one 12 
 * Touchégg version: 2.0.9
 * Operating System: Pop os 21.10
 * GNOME Shell Version: 40.4

**Comment by andirsun** [comment] 2021-11-01 18:15
This is the same laptop but on wayland session

https://user-images.githubusercontent.com/22928302/139720378-6403a610-d9bc-4828-99b5-5f08e1480f08.mp4

**Comment by JoseExposito** [comment] 2021-11-02 16:55
Hola @andirsun 

Thanks for the bug report. The issue is fixed upstream, but it'll need an update on Pop_OS! https://github.com/pop-os/touchegg/issues/3

Closing this one.

**Closed by JoseExposito** 2021-11-02 16:55 UTC

**Comment by JoseExposito** [comment] 2021-11-03 18:11
Oh, I forgot to mention yesterday that, in the meanwhile, you can install Touchégg from the PPA to solve the problem:
https://github.com/JoseExposito/touchegg#ubuntu-debian-and-derivatives
