### ISSUE TITLE
Letters get typed multiple times in Gnome search Bar

### ISSUE THREAD

**Issue by rjkumar1308** [JoseExposito/gnome-shell-extension-x11gestures#18] opened 2021-07-27 13:09 UTC
### Describe the bug

When this extension is enabled then in the gnome search bar the first letter is getting typed multiple times. Sometimes it get typed twice, or more ,or increase after some time, until I reboot, after which it seems to be working correctly; only to face the same issue again.

### Expected behaviour

The first letter is typed only one time.

### Actual behaviour

The first letter is typed multiple times.

### Your environment

 * Extension version: 10
 * Touchégg version: v2.0.11
 * Operating System: Fedora 34
 * GNOME Shell Version: 40.1

### Screenshot
I only pressed 'a' key once.
![Screenshot from 2021-07-27 18-37-12](https://user-images.githubusercontent.com/41501003/127158694-df363ec1-ff7e-41ce-9755-5f2449c5e0e4.png)

**Comment by JoseExposito** [comment] 2021-07-28 11:47
Hi @rjkumar1308 

Thanks for reporting this bug.

Are you using any other extension in addition to X11Gestures? If so, do you mind to disable all of them, with the exception of X11Gestures, and check that you can reproduce the issue?

Let's see if it is a bug using this extension or some weird interaction between different extensions.

**Comment by rjkumar1308** [comment] 2021-07-29 10:32
I will test it with different extensions and let you know in few days. This extension alone is not causing this bug.

**Comment by rjkumar1308** [comment] 2021-07-29 15:13
Its happening with "dash-to-dock" extension.

I followed these steps to install dash-to-dock in fedora 34

1 - sudo dnf install ruby-devel zlib-devel 
2 - sudo su -c "gem install sass" 
3 - git clone https://github.com/ewlsh/dash-to-dock/ 
4 - cd dash-to-dock/ 
5 - git checkout ewlsh/gnome-40 
6 - export SASS=ruby 
7 - make 
8 - make install

**Comment by JoseExposito** [comment] 2021-07-29 15:33
Hi, thanks for testing.

Does the problem also happen if you disable X11Gestures and leave Dash To Dock active?

My guess is this is a bug in Dash To Dock (it looks like it is in beta?) because X11Gestures doesn't change the search bar. Maybe it is worth it reporting in in the Dash To Dock bug tracker.

**Comment by rjkumar1308** [comment] 2021-07-29 16:15
When X11Gestures is disable and Dash To Dock is enabled, I am not getting this issue.

I will report it in Dash To Dock. Should I close this issue?

**Comment by JoseExposito** [comment] 2021-07-29 17:06
Thanks, lets leave it open for the moment until we get some feedback from Dash to Dock devs :)

**Comment by harshadgavali** [comment] 2021-08-05 03:05
This is issue with gnome-shell itself https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4004 .
Which was fixed upstream.

**Comment by JoseExposito** [comment] 2021-08-05 06:10
Thanks for letting me know, closing this issue then.

**Closed by JoseExposito** 2021-08-05 06:10 UTC
