### ISSUE TITLE
failure on nixos

### ISSUE THREAD

**Issue by Vertecedoc4545** [JoseExposito/gnome-shell-extension-x11gestures#19] opened 2021-07-30 06:39 UTC
### Describe the bug
once installed the packages gnome.gnome-shell-extensions gnomeExtensions.x11-gestures and touchegg 
when is activated say touchegg is not installed but is allready installed
(the nixos package management is to diferent and may be the case of the error
### Expected behaviour

that detects installed touchegg

```

Attach Touchégg configuration, placed at `~/.config/touchegg/touchegg.conf`, if you consider it
relevant.

### Your environment

 * Extension version: 8
 * Touchégg version: 1.1.1
 * Operating System: nixos
 * GNOME Shell Version: 40.1
 ## my /etc/default.nix and packages.nix
# default.nix
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
      ./packages.nix
    ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  # Add ZFS support.
  boot.supportedFilesystems = ["zfs"];
  boot.loader.efi.efiSysMountPoint = "/boot/efi";
  boot.initrd.supportedFilesystems = ["zfs"]; # boot from zfs
  boot.loader.generationsDir.copyKernels = true ;
  boot.loader.generic-extlinux-compatible.configurationLimit = 10 ;
  boot.loader.grub.copyKernels = true;  
  boot.zfs.enableUnstable = true;
  boot.kernelPackages = pkgs.linuxPackages_latest;
    
  networking.hostName = "ZFSnixOS"; # Define your hostname.
  networking.networkmanager.enable= true;  # Enables wireless support via wpa_supplicant.

  # Set your time zone.
  time.timeZone = "America/Mexico_City";

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking.useDHCP = false;
  networking.hostId = "f054c846";
  networking.interfaces.enp0s31f6.useDHCP = true;
  networking.interfaces.wlp2s0.useDHCP = true;

  
  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Select internationalisation properties.
  i18n.defaultLocale = "es_MX.UTF-8";
   console = {
     font = "Lat2-Terminus16";
     keyMap = "la-latin1";
   };

  # Enable the X11 windowing system.
  services.xserver.enable = true;

  programs.sway.enable = true;  # Enable the GNOME Desktop Environment.
  services.xserver.displayManager.lightdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;
  services.xserver.windowManager = {
   qtile.enable = true;
   xmonad.enable = true;
   xmonad.enableContribAndExtras = true;
   xmonad.extraPackages = hpkgs: [
     hpkgs.xmonad
     hpkgs.xmonad-contrib
     hpkgs.xmonad-extras
   ];
  };
  hardware.opengl.extraPackages = with pkgs; [ vaapiIntel libvdpau-va-gl vaapiVdpau intel-ocl ];
  hardware.opengl.driSupport = true;
  hardware.opengl.driSupport32Bit = true;
  
  # nguages   = [ "eng" ];
  #   symbolsFile = /yourpath/symbols/us-greek;
  #   }Configure keymap in X11

 # services.xserver.extraLayouts.dvorak_thinkpad = {
 #        description = "a dvorak keybord for thinkpads";
 #          languages   = [ "esp" ];
 #            symbolsFile = /home/carlos/dvorak_thinkpad;
 # };
  

  services.xserver.layout = "latam";
  services.xserver.xkbVariant = "dvorak";
  # services.xserver.xkbOptions = "eurosign:e";

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Enable sound.
  sound.enable = true;
  hardware.pulseaudio.enable = true;
  programs.fish.enable = true;

  # Enable touchpad support (enabled default in most desktopManager).
  services.xserver.libinput.enable = true;

  # Define a user account. Don't forget to set a password with ‘passwd’.
   users.users.carlos = {
     isNormalUser = true;
     extraGroups = [ "wheel" "networkmanager" "floppy" "audio" "video" "cdroom" ]; # Enable ‘sudo’ for the user.
     shell = pkgs.fish;
   };

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  nixpkgs.config = {
    allowUnfree = true; 
  };

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  programs.mtr.enable = true;
  programs.gnupg.agent = {
  enable = true;
  enableSSHSupport = true;
 };

  # List services that you want to enable:

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  networking.firewall.enable = false;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "21.05"; # Did you read the comment?
}


# packages.nix
{ config, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
  #   vim # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
     git
     kakoune
     emacs
     fish
     cmatrix
     ulauncher
     kitty
     wget
     firefox
     rofi
     libreoffice-fresh
     picom
     nitrogen
     discord
     neofetch
     gnomeExtensions.x11-gestures
     gnome.gnome-shell-extensions
     gnome.gnome-tweaks
     touchegg
  ];
}








### why?
just follow the nixos instalation guide with this config (change the keyboard layout, it's in dvorak)
and change the root file system mine is actually ZFS

**Comment by JoseExposito** [comment] 2021-07-30 07:08
Hi,

This extension checks that Touchégg config is available to display, or not, the "not installed" notification.

I've never used NixOS, but, I believe it doesn't have a `/usr` folder, that's why you are seeing this error.

As Touchégg was packaged for NixOS by @Hvassaa and @jtojnar, lets see if they can help here :)
https://github.com/JoseExposito/touchegg/pull/467

**Comment by jtojnar** [comment] 2021-08-06 15:04
It looks like the touchegg fixes from the PR are not available in Nixpkgs yet, see https://github.com/NixOS/nixpkgs/pull/116393 for relevant downstream PR.

@Vertecedoc4545 when you experience a problem in the future, please open an issue against your distro’s issue tracker first, unless you are certain that the problem is not due to packaging.

**Comment by JoseExposito** [comment] 2021-08-06 16:07
Thanks a lot for your input @jtojnar. Closing the issue.

**Closed by JoseExposito** 2021-08-06 16:07 UTC
